let configuredData = [
    {
        "id": "594",
        "Distance": "12076",
        "Status": "ONLINE",
        "StatusDetail": "4 days ago",
        "Name": "oilnayor0466",
        "SN / MAC": "HWTC02563FA6",
        "ONU": "TH-MDH-DNS-02 gpon-onu_0/0/7:8",
        "Zone": "P02-LK",
        "ODB": "None",
        "Signal": "good",
        "B/R": "Router",
        "VLAN": "105",
        "VoIP": "",
        "TV": "",
        "Type": "HG8010C",
        "Auth date": "08-Apr-2023 11:46:55",
        "OLT": "TH-MDH-DNS-02",
        "Board": "0",
        "Port": "7",
        "ONUView": "gpon-onu_0/0/7:8",
        "Address or comment": "None",
        "ONU/OLT Rx signal": "-23.46 dBm / -27.96 dBm (12076m)",
        "Signal Value": "-23.46 dBm",
        "ONU mode": "Routing - WAN vlan: 105",
        "Mgmt IP": "Inactive",
        "WAN setup mode": "Setup via ONU webpage",
        "Service-port ID": "753",
        "Download": "1G",
        "Upload": "1G",
        "EthernalAll": [
            {
                "EthernetPort": "eth_0/1",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            }
        ],
        "img": "https://atelfiber.smartolt.com/content/img/1_eth_0_voip_0_catv.png",
        "traffic img": "/images/mockup/594-traffic.png",
        "signal img": "/images/mockup/594-signal.png"
    },
    {
        "id": "592",
        "Distance": "6242",
        "Status": "ONLINE",
        "StatusDetail": null,
        "Name": "STdesign",
        "SN / MAC": "HWTC66730B9F",
        "ONU": "OLT-Parnter-A gpon-onu_0/1/0:5",
        "Zone": "Zone-OLT-Parnter-A",
        "ODB": "None",
        "Signal": "good",
        "B/R": "Bridge",
        "VLAN": "10",
        "VoIP": "",
        "TV": "",
        "Type": "HG8010H",
        "Auth date": "02-Apr-2023 12:50:18",
        "OLT": "OLT-Parnter-A",
        "Board": "1",
        "Port": "0",
        "ONUView": "gpon-onu_0/1/0:5",
        "Address or comment": "None",
        "ONU/OLT Rx signal": "-14.62 dBm / -19.14 dBm (6242m)",
        "Signal Value": "-14.62 dBm",
        "ONU mode": "Bridging - Main vlan: 10",
        "Mgmt IP": "Inactive",
        "WAN setup mode": null,
        "Service-port ID": "19",
        "Download": "1G",
        "Upload": "1G",
        "EthernalAll": [
            {
                "EthernetPort": "eth_0/1",
                "Admin state": "enabled",
                "Mode": "Access VLAN: 10",
                "DHCP": "No control",
            }
        ],
        "img": "https://atelfiber.smartolt.com/content/img/1_eth_0_voip_0_catv.png",
        "traffic img": "/images/mockup/592-traffic.png",
        "signal img": "/images/mockup/592-signal.png"
    },
    {
        "id": "414",
        "Distance": "8963",
        "Status": "ONLINE",
        "StatusDetail": null,
        "Name": "Pattarawadeekok2",
        "SN / MAC": "HWTC0A889EA0",
        "ONU": "TH-MDH-DNS-02 gpon-onu_0/0/5:32",
        "Zone": "TH-MDH-DTN-01",
        "ODB": "None",
        "Signal": "critical",
        "B/R": "Router",
        "VLAN": "105",
        "VoIP": "",
        "TV": "CATV",
        "Type": "HG8245W5",
        "Auth date": "03-Mar-2022 16:07:18",
        "OLT": "TH-MDH-DNS-02",
        "Board": "0",
        "Port": "5",
        "ONUView": "gpon-onu_0/0/5:32",
        "Address or comment": "None",
        "ONU/OLT Rx signal": "-27.21 dBm / -33.02 dBm (8964m)",
        "Signal Value": "-27.21 dBm",
        "ONU mode": "Routing - WAN vlan: 105",
        "Mgmt IP": "Inactive",
        "WAN setup mode": "Setup via ONU webpage",
        "Service-port ID": "1057",
        "Download": "1G",
        "Upload": "1G",
        "EthernetPort": "eth_0/1",
        "Admin state": "enabled",
        "Mode": "Access VLAN: 10",
        "DHCP": "No control",
        "EthernalAll": [
            {
                "EthernetPort": "eth_0/1",
                "Admin state": "enabled",
                "Mode": "Access VLAN: 10",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/2",
                "Admin state": "enabled",
                "Mode": "Access VLAN: 10",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/3",
                "Admin state": "enabled",
                "Mode": "Access VLAN: 10",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/4",
                "Admin state": "enabled",
                "Mode": "Access VLAN: 10",
                "DHCP": "No control",
            }
        ],
        "img": "https://atelfiber.smartolt.com/content/img/4_eth_2_voip_1_catv.png",
        "traffic img": "/images/mockup/414-traffic.png",
        "signal img": "/images/mockup/414-signal.png"
    },
    {
        "id": "445",
        "Distance": "-",
        "Status": "UNPLUG",
        "StatusDetail": null,
        "Name": "apiwatnayor20465",
        "SN / MAC": "HWTC06BBD4A0",
        "ONU": "TH-MDH-DNS-02 gpon-onu_0/0/6:58",
        "Zone": "TH-MDH-DTN-01",
        "ODB": "None",
        "Signal": "-",
        "B/R": "Router",
        "VLAN": "105",
        "VoIP": "",
        "TV": "CATV",
        "Type": "HG8245W5",
        "Auth date": "21-Apr-2022 14:13:25",
        "OLT": "TH-MDH-DNS-02",
        "Board": "0",
        "Port": "6",
        "ONUView": "gpon-onu_0/0/6:58",
        "Address or comment": "None",
        "ONU/OLT Rx signal": "-",
        "Signal Value": "-",
        "ONU mode": "Routing - WAN vlan: 105",
        "Mgmt IP": "Inactive",
        "WAN setup mode": "Setup via ONU webpage",
        "Service-port ID": "1102",
        "Download": "1G",
        "Upload": "1G",
        "EthernalAll": [
            {
                "EthernetPort": "eth_0/1",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/2",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/3",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/4",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            }
        ],
        "img": "https://atelfiber.smartolt.com/content/img/4_eth_2_voip_1_catv.png",
        "traffic img": "/images/mockup/445-traffic.png",
        "signal img": "/images/mockup/445-signal.png"
    },
    {
        "id": "505",
        "Distance": "-",
        "Status": "LOSS",
        "StatusDetail": null,
        "Name": "Lamduenkame",
        "SN / MAC": "HWTC1A8C9AA1",
        "ONU": "TH-MDH-DNS-02 gpon-onu_0/0/2:61",
        "Zone": "TH-MDH-DTN-01",
        "ODB": "None",
        "Signal": "-",
        "B/R": "Router",
        "VLAN": "105",
        "VoIP": "",
        "TV": "CATV",
        "Type": "HG8245W5",
        "Auth date": "07-Oct-2022 17:50:33",
        "OLT": "TH-MDH-DNS-02",
        "Board": "0",
        "Port": "0",
        "ONUView": "gpon-onu_0/0/0:92",
        "Address or comment": "None",
        "ONU/OLT Rx signal": "-",
        "Signal Value": "-",
        "ONU mode": "Routing - WAN vlan: 105",
        "Mgmt IP": "Inactive",
        "WAN setup mode": "Setup via ONU webpage",
        "Service-port ID": "1240",
        "Download": "1G",
        "Upload": "1G",
        "EthernalAll": [
            {
                "EthernetPort": "eth_0/1",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/2",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/3",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            },
            {
                "EthernetPort": "eth_0/4",
                "Admin state": "enabled",
                "Mode": "LAN",
                "DHCP": "No control",
            }
        ],
        "img": "https://atelfiber.smartolt.com/content/img/4_eth_2_voip_1_catv.png",
        "traffic img": "/images/mockup/505-traffic.png",
        "signal img": "/images/mockup/505-signal.png"
    },
]

export { configuredData }